# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UnitTestCoverage
on:
  push:
    branches: [ master, java-build-tests ]
  pull_request:
    branches: [ master ]

permissions:
  id-token: write
  contents: read

jobs:
#  build:
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        python-version: [3.8, 3.9, "3.10", 3.11]
#        os: [ubuntu-latest, macOS-latest, windows-latest ]
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python ${{ matrix.python-version }}
#      uses: actions/setup-python@v2
#      with:
#        python-version: ${{ matrix.python-version }}
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#        pip install -r test_requirements.txt
#    - name: Test with pytest
#      run: |
#        pytest
  running_sample:
    # needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        python-version: [ 3.8, 3.9, "3.10", 3.11 ]
#        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        python-version: [ 3.8, 3.9 ]
        os: [ ubuntu-latest, macOS-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_GHWF }}
          role-session-name: myGitHubActions

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'corretto'

      - name: Install Python and required pips
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_requirements.txt

      - name: Install jar files
#        run: |
#          python setup.py download_jars
#          python setup.py install
        run: |
          python setup.py download_jars

      - name: Put words to sample stream
        run: sample_kinesis_wordputter.py --stream kclpysample -w cat -w dog -w bird -w lobster -w octopus

      #backtocks didn't work on the command? raises an error in workflows, just prints the command without the backticks
#      - name: Start KCL application
#        run: $(amazon_kclpy_helper.py --print_command --java $(which java) --properties samples/sample.properties)

